export const ROUTE_APP_NAVIGATOR = 'ROUTE_APP_NAVIGATOR';
export const ROUTE_GUEST_NAVIGATOR = 'ROUTE_GUEST_NAVIGATOR';
export const ROUTE_HOME_NAVIGATOR = 'ROUTE_HOME_NAVIGATOR';
export const ROUTE_PROFILE_NAVIGATOR = 'ROUTE_PROFILE_NAVIGATOR';
export const ROUTE_LOGIN = 'ROUTE_LOGIN';
export const ROUTE_REGISTER = 'ROUTE_REGISTER';
export const ROUTE_HOMEPAGE = 'ROUTE_HOMEPAGE';
export const ROUTE_HOMEPAGE_SECOND_SCREEN = 'ROUTE_HOMEPAGE_SECOND_SCREEN';

export const DETAILS = 'DETAILS';

